### ISSUE TITLE
Cordova Persistence Storage

### ISSUE THREAD

**Issue by AdobeWordPress** [mar10/persisto#1]
### Environment
  - Browser type and version:  Cordova IOS and Android Platforms
  - jQuery version: 3.2.1
  - persisto version: X

Hello everyone.

I developed a hybrid mobile app for IOS and Android platforms with Cordova. I'm also using jQuery for functionality and localStorage for saving some data. I already uploaded my app to AppStore. This week I released my first update but after app update, all of the datas which stored on devices are wiped. After quick research, I figured out that IOS resets localstorage when you update your app. 

Now I'm looking for persistent and synchronous storage. Can I use persisto with Cordova? Will the data stored with Persisto disappear after updating the application? 

Best.

**Comment by mar10** [comment]
Persisto is a wrapper around localStorage / sessionStorage, so all restrictions apply.

I didn't work with Cordova yet, but it seems, that they [recommend misc. external storage type](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html) each with pros and cons.
Which technology did you have in mind.

(Btw. a similar request was made here mar10/fancytree#808 for Fancytree and the electron platform. But I am not sure if store.js would solve your problem)

**Comment by AdobeWordPress** [comment]
Thank you very much. I think Persisto would not provide a permanent storage solution for Cordova.
