### ISSUE TITLE
Writing file input fields raises exception

### ISSUE THREAD

**Issue by tobias-tr** [mar10/persisto#3]
Hi,

is it possible to skip ```<input type="file">``` elements when using "readFromForm" and "writeToForm"?

Chrome throws:
Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

All elements after this one are skipped, when using readFromForm.

### Environment

  - Browser type and version: Google Chrome 80.0.3987.149
  - jQuery version: 3.3.1
  - persisto version: 1.2.0

**Comment by mar10** [comment]
Hi,
Did you set the `addNew: true` option? Can you share some debuggable code?

**Comment by tobias-tr** [comment]
Hi, I tried to set up a jsfiddle, hope it works, it is the first time I used it...

https://jsfiddle.net/jjoker/ufnkwe26/3/

* Enter a value in all input fields, and choose a file for upload.
* press "Save"
* press "Clear"
* press "Load"

**Comment by mar10** [comment]
This is probably easy to fix in the code, but I don't plan a release in the next future, sorry.

However, you can workaround this by preventing `addNew` and explicitly listing the fields:
```js
var settingsStore = new PersistentObject("neues-portal", {
        debugLevel:2,
        defaults: {
          input1: "",
          input3: ""
        }
      });
...
function saveForm() {
    settingsStore.readFromForm("#frmNeuesPortal", { addNew: false });
}
```

**Comment by tobias-tr** [comment]
Ok. I have more than 50 input fields, so this is not really a good solution.
I have done the following workaround, about line 550
```
         } else if ($input.is("select")) {
            // listbox
            $input.find("option").each(function() {
              $(this).prop(
                "selected",
                $.isArray(v) ? $.inArray(this.value, v) >= 0 : this.value === v
              );
            });
          } else if (type === "file") {
            // skip type=file
          } else {
            $input.val(v);
          }
```

**Comment by mar10** [comment]
Yes, this is an obvious fix, I committed it, thanks.
